version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "bundler"
    directory: "/"  # The root directory where your Gemfile is located
    schedule:
      interval: "monthly" # Options: "daily", "weekly", "monthly"